# Advanced NumPy

In [407]:
%pylab inline

import numpy as np
from numpy.random import randn

import pandas as pd
from pandas import Series, DataFrame

Populating the interactive namespace from numpy and matplotlib


## ndarray Object Internals

NumPy ndarray 提供了一种将同质数据块解释为多维数组对象的方式

ndarray 内部有以下组成
- 一个指向数组的指针
- 数据类型 dtype
- 一个表示数组形状的元组 tuple
- 一个跨度元组 stride。例如 3x4x5 float64 数组，跨度为 (160, 40, 8)

In [408]:
np.empty((3,4,5), dtype='f8').strides

(160, 40, 8)

### NumPy dtype Hierarchy

In [409]:
ints = np.ones(10, dtype='i2')
floats = np.ones(10, dtype='f4')

In [410]:
np.issubdtype(ints.dtype, np.integer)

True

In [411]:
np.issubdtype(floats.dtype, np.floating)

True

In [412]:
# 调用 dtype 的 mro 方法查看所有父类
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

## Advanced Array Manipulation
### Reshaping Arrays

In [413]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [414]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [415]:
# 作为参数的形状其中一维可以是 -1，表示该维度大小有数据本身推断
arr.reshape((-1,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [416]:
# 数组shape属性是一个 tuple, 可以当参数传入reshape
other_arr = np.ones((3,5))

arr = np.arange(15)
arr = arr.reshape(other_arr.shape)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [417]:
#  ravel 为 reshape 反运算，将数组扁平化
arr1 = arr.ravel()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [418]:
# flatten 类似 ravel，但返回数据副本
arr2 = arr.flatten()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [419]:
arr1[1] = 111
arr2[2] = 222

# 修改arr2(副本)不会改变arr
arr, arr1, arr2

(array([[  0, 111,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14]]),
 array([  0, 111,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14]),
 array([  0,   1, 222,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14]))

### C versus Fortran Order

In [420]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [421]:
# C: row first
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [422]:
# Fortran: column first
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [423]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

# 预设沿着 axis=0 连接
np.concatenate([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [424]:
# 沿着 axis=1 连接
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [425]:
# 等同于 concatenate(axis=0)
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [426]:
# 等同于 concatenate(axis=1)
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [427]:
arr = np.arange(5).reshape((5,1))

# 沿着 axis=0，拆分数组
first, second, third = np.split(arr, [1,3])

In [428]:
first

array([[0]])

In [429]:
second

array([[1],
       [2]])

In [430]:
third

array([[3],
       [4]])

数组连接函数

函数 | 说明
---|---
`concatenate` | 一般化的连接
`vstack`, `row_stack` | 沿轴0进行堆叠
`hstack` | 沿轴1进行堆叠
`column_stack` | 类似 `hstack`, 但是会先将一维数组转换为二维列向量
`dstack` | 以面向“深度”的方式对数组进行堆叠（沿轴2)
`split` | 沿指定轴在指定的位置拆分数组
`hsplit`, `vsplit`, `dsplit` | split便捷化函数，分别沿轴0,1,2进行拆分

In [431]:
arr1 = np.array([1,2,3,4]).reshape((2,2))
arr2 = np.array([5,6,7,8]).reshape((2,2))

In [432]:
vs = np.vstack([arr1, arr2])
vs

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [433]:
hs = np.hstack([arr1, arr2])
hs

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [434]:
np.column_stack([arr1, arr2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [435]:
cube = np.dstack([arr1, arr2])
cube

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [436]:
for arr in np.vsplit(vs, 2):
    print arr

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [437]:
for arr in np.hsplit(hs, 2):
    print arr

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [438]:
# dstack, dsplit 不是反函数？
for arr in np.dsplit(cube, [2]):
    print arr

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
[]


#### Stacking helpers: `r_` and `c_`

使数组的堆叠操作更简洁

In [439]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = randn(3,2)

In [440]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.31341143, -0.55743138],
       [ 0.89148647, -0.6508946 ],
       [ 1.33041068, -0.98239484]])

In [441]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -0.31341143, -0.55743138],
       [ 2.        ,  3.        ,  0.89148647, -0.6508946 ],
       [ 4.        ,  5.        ,  1.33041068, -0.98239484]])

In [442]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.31341143, -0.55743138,  3.        ],
       [ 0.89148647, -0.6508946 ,  4.        ],
       [ 1.33041068, -0.98239484,  5.        ]])

In [443]:
# 将切片翻译成数组
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: Tile and Repeat

因为广播（broadcasting），NumPy 很少需要对数组进行重复（replicate）

In [444]:
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [445]:
# 传入数组，指定重复次数
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [446]:
arr = np.arange(4).reshape((2,2))

# 沿指定轴重复
arr.repeat(2, axis=0)

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 3]])

In [447]:
arr.repeat(2, axis=1)

array([[0, 0, 1, 1],
       [2, 2, 3, 3]])

In [448]:
# 传入数组，指定重复次数
arr.repeat([2,3], axis=0)

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 3],
       [2, 3]])

In [449]:
# 沿指定轴，堆叠数组的副本数（像铺瓷砖）
np.tile(arr, 3)

array([[0, 1, 0, 1, 0, 1],
       [2, 3, 2, 3, 2, 3]])

In [450]:
# 第二个参数可以是表示布局的 tuple，
np.tile(arr, (3,2))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])

### Fancy Indexing Equivalents: Take and Put

In [451]:
arr = np.arange(10) * 100

# 透过整数数组使用花式索引
inds = [7,1,2,6]
arr[inds]

array([700, 100, 200, 600])

In [452]:
# 获取单个轴向的选区
arr.take(inds)

array([700, 100, 200, 600])

In [453]:
# 设置单个轴向的选区
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [454]:
arr.put(inds, [11,22,33,44])
arr

array([  0,  22,  33, 300, 400, 500,  44,  11, 800, 900])

In [455]:
inds = [2,0,2,1]
arr = np.arange(2*4).reshape((2,4))

# 沿着 axis=1 选取
arr.take(inds, axis=1)

array([[2, 0, 2, 1],
       [6, 4, 6, 5]])

## Broadcasting

In [456]:
arr = np.arange(5)

# 标量被广播到所有元素上
arr * 4

array([ 0,  4,  8, 12, 16])

In [457]:
arr = randn(4,3)

# 沿轴0，计算平均
means = arr.mean(axis=0)

# 沿轴0，广播
demeaned = arr - means

# 验证
demeaned.mean(0)

array([  2.77555756e-17,   0.00000000e+00,   0.00000000e+00])

In [458]:
# 沿轴1，计算平均
row_means = arr.mean(1)

# 沿轴1，广播
demeaned = arr - row_means.reshape((4,1))

# 验证
demeaned.mean(1)

array([  0.00000000e+00,   7.40148683e-17,  -1.85037171e-17,
         0.00000000e+00])

### Broadcasting Over Other Axes

In [459]:
# 以下会引发错误（维度不对）
# arr - arr.mean(1)

arr.shape, arr.mean(1).shape

((4, 3), (4,))

In [460]:
# 根据广播原则，较小数组的“广播维”必须是1。
# 上面的例子，要将平均值的形状由(4,)变成(4,1)
arr - arr.mean(1).reshape((4,1))

array([[ 0.00611864, -0.6988954 ,  0.69277676],
       [-1.68118647,  1.30501219,  0.37617428],
       [ 0.66517793, -0.55176232, -0.11341561],
       [ 0.44447587,  0.45831871, -0.90279458]])

#### 使用 np.newaxis 插入新轴

In [461]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [462]:
arr.shape

(3,)

In [463]:
# 插入 axix=1 的新轴
arr_2d = arr[:, np.newaxis]
arr_2d

array([[0],
       [1],
       [2]])

In [464]:
arr_2d.shape

(3, 1)

In [465]:
# 插入 axix=0 的新轴
arr_2d = arr[np.newaxis, :]
arr_2d

array([[0, 1, 2]])

In [466]:
arr_2d.shape

(1, 3)

In [467]:
arr = np.arange(4).reshape((2,2))

# 插入 axix=1 的新轴（很难像像...）
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(2, 1, 2)

In [468]:
arr = randn(3,4,5)

# 沿轴2，计算平均
means_axis2 = arr.mean(2)

# 沿轴2，广播平均值
demeaned = arr - means_axis2[:, :, np.newaxis]

# 验证
demeaned.mean(2)

array([[  0.00000000e+00,  -6.66133815e-17,   6.66133815e-17,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  6.66133815e-17,  -8.88178420e-17,  -1.66533454e-17,
          7.77156117e-17]])

### Setting Array Values by Broadcasting

In [469]:
arr = np.zeros((4,3))

# 使用索引设置数组
# 使用[:]表示对数组操作，不让会变成赋值
arr[:] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [470]:
col = np.array([1,2,3,4])

# 沿 axis=1 广播
arr[:] = col[:, np.newaxis]
arr

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.]])

In [471]:
row = np.array([1,2,3])

# 沿 axis=0 广播
arr[:] = row[np.newaxis, :]
arr

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [472]:
# row 0,1 赋值
arr[:2] = 5
arr

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [473]:
# row 0,1 赋值
arr[:2] = [[6],[7]]
arr

array([[ 6.,  6.,  6.],
       [ 7.,  7.,  7.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [474]:
# row 0,1 赋值
arr[:2] = [[2,3,4], [4,5,6]]
arr

array([[ 2.,  3.,  4.],
       [ 4.,  5.,  6.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

## Advanced ufunc Usage
### ufunc Instance Methods

ufunc 的方法

方法 | 说明
---|---
`reduce(x)` | 通过连续执行原始运算的方式进行聚合
`accumulate(x)` | 聚合值，保留所有局部聚合结果
`reduceat(x, bins)` | ”局部“约简（groupby），约简数据的各个切片以产生聚合型数组
`outer(x, y)` | 对x和y中的每个元素应用原始运算，结果数组的形状为 (x.shape, y.shape)。计算两个数组的叉积

In [475]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [476]:
np.add.reduce(arr)

45

In [477]:
np.add.accumulate(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [478]:
np.add.reduceat(arr, [0,5,8]) 

array([10, 18, 17])

In [479]:
np.multiply.outer(np.arange(1,10), np.arange(1,10)) # 九九乘法

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Custom ufuncs

In [480]:
def add_element(x,y):
    return x+y

# frompyfunc: 接受一个Python函数，以及两个分别表示输入、输出参数数量的整数
add_them = np.frompyfunc(add_element, 2, 1)

add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [481]:
arr = randn(1000)

In [482]:
%timeit add_them(arr, arr) # 纯python运算，效率不好

1000 loops, best of 3: 180 µs per loop


In [483]:
%timeit np.add(arr, arr)

The slowest run took 23.93 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.01 µs per loop


## Structured and Record Arrays

In [484]:
# 结构化数组是一种特殊的 ndarray (类似C语言给的struct)
dtype = [('x', np.float64), ('y', np.int32)]

sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

array([(1.5, 6), (3.141592653589793, -2)], 
      dtype=[('x', '<f8'), ('y', '<i4')])

In [485]:
# 字段名保存在dtype.names属性中
sarr.dtype.names

('x', 'y')

### Nested dtypes and Multidimensional Fields

In [486]:
# x 字段是一个长度为3的数组
dtype = [('x', np.float64, 3), ('y', np.int32)]

arr = np.zeros(4, dtype=dtype)
arr

array([([0.0, 0.0, 0.0], 0), ([0.0, 0.0, 0.0], 0), ([0.0, 0.0, 0.0], 0),
       ([0.0, 0.0, 0.0], 0)], 
      dtype=[('x', '<f8', (3,)), ('y', '<i4')])

In [487]:
arr[0]['x']

array([ 0.,  0.,  0.])

In [488]:
arr['x']

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [489]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', 'i4')]

data = np.array([((1, 2), 5), ((3, 4), 6)], dtype = dtype)
data

array([((1.0, 2.0), 5), ((3.0, 4.0), 6)], 
      dtype=[('x', [('a', '<f8'), ('b', '<f4')]), ('y', '<i4')])

In [490]:
data['y']

array([5, 6], dtype=int32)

In [491]:
data['x']['a']

array([ 1.,  3.])

### Why Use Structured Arrays?

NumPy 结构化数组每个元素在内存中被表示为固定的字节数，可以非常快速高效读写

### Structured Array Manipulations: numpy.lib.recfunctions

NumPy 模块 numpy.lib.recfuncitons 中有一些用于增删字段或执行基本连接运算的工具

## More About Sorting

In [492]:
arr = randn(6)

# 数组内容重新排列，不会产生新数组
arr.sort()
arr

array([-1.1639929 , -0.98304986, -0.7521401 ,  0.70613548,  0.73075806,
        1.51136215])

In [493]:
arr = randn(3,4)
arr

array([[ 0.31330777, -1.40890127,  1.26406942,  1.22833342],
       [-0.03860545, -0.38530001, -0.42328541, -0.5776526 ],
       [ 0.38456117, -0.51642746, -1.11442741, -1.39050972]])

In [494]:
arr[:, 0].sort() # sort first column values in-place
arr

array([[-0.03860545, -1.40890127,  1.26406942,  1.22833342],
       [ 0.31330777, -0.38530001, -0.42328541, -0.5776526 ],
       [ 0.38456117, -0.51642746, -1.11442741, -1.39050972]])

In [495]:
arr = np.array([1,3,5,2,4])

# numpy.sort 会创建一个已排序副本
np.sort(arr), arr

(array([1, 2, 3, 4, 5]), array([1, 3, 5, 2, 4]))

In [496]:
arr = np.array([[6,4,2],[5,3,1]])

# 沿轴1排序
arr.sort(axis=1)
arr

array([[2, 4, 6],
       [1, 3, 5]])

In [497]:
# 沿轴0排序
arr.sort(axis=0)
arr

array([[1, 3, 5],
       [2, 4, 6]])

In [498]:
# sort 排序不可设置为降序。但数组切片会产生视图，values[::-1]可以返回反序列表
arr[:, ::-1]

array([[5, 3, 1],
       [6, 4, 2]])

### Indirect Sorts: argsort and lexsort

In [499]:
values = np.array([5,0,1,3,2])

# 取得排序数据的索引数组
indexer = values.argsort()
values[indexer]

array([0, 1, 2, 3, 5])

In [500]:
arr = randn(3,5)
arr[0] = values
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-1.25751525,  0.11903687, -0.32125962, -2.36234913,  1.04582681],
       [ 0.73770923, -0.10817077, -0.47392602, -0.86279211,  0.15106823]])

In [501]:
# 根据 row 0 数组排序 columns
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.11903687, -0.32125962,  1.04582681, -2.36234913, -1.25751525],
       [-0.10817077, -0.47392602,  0.15106823, -0.86279211,  0.73770923]])

In [502]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

# lexsort 可以一次性对多个键数组执行间接排序
# 键的应用顺序是从最后一个传入的算起
sorter = np.lexsort((first_name, last_name))
zip(last_name[sorter], first_name[sorter])

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### Alternate Sort Algorithms

数组排序算法

kind | 速度 | 稳定性 | 工作空间 | 最坏情况
---|---|---|---|---
`quicksort` | 1 | 否 | 0 | O(n<sup>2</sup>)
`mergesort` | 2 | 是 | n/2 | O(n log n) 
`heapsort`  | 3 | 否 | 0 | O(n log n)

In [503]:
arr = np.array([2,2,1,1,1])

# mergesort 会保持等价元素的相对位置
arr.argsort(kind='mergesort')

array([2, 3, 4, 0, 1])

### numpy.searchsorted: Finding elements in a Sorted Array

In [504]:
arr = np.array([0,1,7,12,15])

# 返回插值位置，插值后数组依然维持有序性
arr.searchsorted(9)

3

In [505]:
# 返回一组索引
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5])

In [506]:
arr = np.array([0,0,0,1,1,1,1])

# 返回等值组左侧索引
arr.searchsorted([0,1])

array([0, 3])

In [507]:
# 返回等值组右侧索引
arr.searchsorted([0,1], side='right')

array([3, 7])

In [508]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])

# 使用一个表示“面元边界”的数组，用它拆分数组
labels = bins.searchsorted(data)
labels

array([4, 3, 2, 4, 3, 3, 2, 3, 3, 4, 4, 2, 3, 4, 3, 3, 3, 4, 3, 4, 4, 4, 4,
       2, 4, 3, 3, 3, 4, 4, 3, 4, 3, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3,
       4, 2, 4, 3])

In [509]:
# 通过 groupby 可以轻松对原数据进行拆分
Series(data).groupby(labels).mean()

2     575.333333
3    2781.058824
4    7413.592593
dtype: float64

In [510]:
# 另一种计算面元编号的方法
np.digitize(data, bins)

array([4, 3, 2, 4, 3, 3, 2, 3, 3, 4, 4, 2, 3, 4, 3, 3, 3, 4, 3, 4, 4, 4, 4,
       2, 4, 3, 3, 3, 4, 4, 3, 4, 3, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3,
       4, 2, 4, 4])

## NumPy Matrix Class

In [511]:
X = np.random.randn(4,4)
X

array([[-1.82483812,  0.7707742 , -0.82920182, -1.14220512],
       [ 0.15172241,  0.98559826, -1.64532857,  2.40927434],
       [ 1.78811915, -1.27508111,  2.26139266,  0.23147447],
       [ 0.18929524, -0.80366152, -1.21489601,  0.43152223]])

In [512]:
# [:, 0] 产生一维数组
X[:, 0]

array([-1.82483812,  0.15172241,  1.78811915,  0.18929524])

In [513]:
# [:, :1] 才会产生二维数组
y = X[:, :1]
y

array([[-1.82483812],
       [ 0.15172241],
       [ 1.78811915],
       [ 0.18929524]])

In [514]:
y.T

array([[-1.82483812,  0.15172241,  1.78811915,  0.18929524]])

In [515]:
# 对数组进行矩阵操作需要用到 numpy.dot
np.dot(y.T, np.dot(X, y))

array([[-2.94238892]])

In [516]:
Xm = np.matrix(X)
Xm

matrix([[-1.82483812,  0.7707742 , -0.82920182, -1.14220512],
        [ 0.15172241,  0.98559826, -1.64532857,  2.40927434],
        [ 1.78811915, -1.27508111,  2.26139266,  0.23147447],
        [ 0.18929524, -0.80366152, -1.21489601,  0.43152223]])

In [517]:
# 类似Matlab，单行或列会以二维形式返回
ym = Xm[:, 0]
ym

matrix([[-1.82483812],
        [ 0.15172241],
        [ 1.78811915],
        [ 0.18929524]])

In [518]:
# 使用上较直觉
ym.T * Xm * ym

matrix([[-2.94238892]])

In [519]:
Xm.I * Xm

matrix([[  1.00000000e+00,  -1.66533454e-16,   4.44089210e-16,
          -4.44089210e-16],
        [  2.77555756e-17,   1.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  3.53883589e-16,  -1.11022302e-16,   1.00000000e+00,
           4.44089210e-16],
        [  5.55111512e-17,   1.11022302e-16,  -2.22044605e-16,
           1.00000000e+00]])

- 不建议用 numpy.matrix 替代正规的 ndarray，因为它们的应用面较窄
- 对于个别带有大量线性代数运算的函数，可以将函数参数转为matrix类型，然后在返回之前用 np.asarray（不会复制任何数据）将其转换回正规的 ndarray

In [520]:
Zm = np.matrix(np.zeros((4,4)))

# Z 只是 Zm 的视图
Z = np.asanyarray(Zm)

In [521]:
Z[::2, ::2] = 1
Z[1::2, 1::2] = 1
Z

matrix([[ 1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.],
        [ 1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.]])

In [522]:
Zm

matrix([[ 1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.],
        [ 1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  1.]])

## Advanced Array Input and Output
### Memory-mapped Files
内存映像就是一个存放在磁盘上的 ndarray

In [523]:
# 允许将大文件分成小段进行读写
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000,10000))
mmap

memmap([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [524]:
# 返回数据视图
section = mmap[:5]
section[:] = randn(5, 10000)

In [525]:
mmap.flush()

In [526]:
# 删除 mmap 对象
del mmap

In [527]:
# 打开一个已经存在的内存映像，需指明数据类型和形状
mmap = np.memmap('mymmap', dtype='float64', shape=(10000,10000))
mmap

memmap([[ 0.21759769,  0.70937526,  1.22964025, ..., -0.47545463,
        -0.04366666, -0.71400057],
       [ 0.84242015,  1.60927997,  0.85123145, ..., -0.42153086,
        -0.45684018,  0.27679002],
       [-0.89807123, -1.33199964,  0.28854795, ...,  0.89912403,
         1.00485049,  1.1112015 ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [528]:
!rm -f mymmap

### HDF5 and Other Array Storage Options

PyTable 和 h5py 这两个 Python 项目可以将 NumPy 的数组数据存储为高效且可压缩的HDF5格式 (HDF: hierarchical data format)。可以安全将好几百GB甚至TB的数据存储为HDF5格式

## Performance Tips

- 将 Python 循环和条件逻辑转换成数组运算、布尔数组运算
- 尽量使用广播
- 避免复制数据，尽量使用数组视图（即切片）
- 利用 ufunc 即其各种方法

### The Importance of Contiguous Memory

In [529]:
arr_c = np.ones((1000, 1000), order='C')
arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [530]:
arr_f = np.ones((1000, 1000), order='F')
arr_f.flags


  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [531]:
# 理论上 arr_c 会比 arr_f 快
%timeit arr_c.sum(1)

1000 loops, best of 3: 605 µs per loop


In [532]:
%timeit arr_f.sum(1)

1000 loops, best of 3: 702 µs per loop


In [533]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [534]:
# 构造识图时，结果不一定是连续的
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

### Other Speed Options: Cython, f2py, C

- 将 Cython 看成带有静态类型并能嵌入C函数的Python
- Cython 处理代码，先将其翻译成C代码，然后编译这些C代码并创建一个Python扩展
- Cython 编写只比写纯 Python 代码多花点时间，能跟 NumPy 紧密结合
- 一般工作流程：得到能在 Python 运行的算法，将其翻译成 Cython